// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
)

// Injectors from wire.go:

func initialize(ctx context.Context) Baz {
	bar := NewBar()
	foo := NewFoo()
	baz := NewBaz(bar, foo)
	return baz
}
